### ISSUE TITLE
Error (active)	E0323	function returning abstract class "xlw::CellValue" is not allowed

### ISSUE THREAD

**Issue by mthks** [xlw/xlw#18]
CellValue GetCellValue(const unsigned long i, const CellMatrix &cm) {
	int cols = cm.ColumnsInStructure();
	unsigned long r = (i / cols);
	unsigned long c = (i % cols);
	CellValue cv = cm(r,c);
	return cv;
}

I am getting the "Error (active)	E0323	function returning abstract class "xlw::CellValue" is not allowed" on the first line.

I am converting my old (very large) project from XLW4 (VS2008) to VS2019.  The project was compiling and perfectly under the old version but am now getting a lot of compile errors.

CellValue seems to be an abstract class so I am trying to figure out if should be using another implemented class instead or if I should be implementing this myself.

Also, same question on CellMatrix (as I do see MJCellMatrix also)

Any help is appreciated.

**Comment by Ninds** [comment]
HI


```csharp
CellMatrix GetCellValue(const unsigned long i, const CellMatrix& cm) {
    int cols = cm.ColumnsInStructure();
    unsigned long r = (i / cols);
    unsigned long c = (i % cols);
    CellMatrix result(1, 1);
    result(0,0) = cm(r, c);
    return result;
}
```
