### ISSUE TITLE
How use it in C#

### ISSUE THREAD

**Issue by lqexceldev** [xlw/xlw#3]
How is referenced in csharp or is only valid in C++? The syntax is idem to before versions?

**Comment by Ninds** [comment]
Hi,
C# support is imminent. We are currently testing the .NET package. 

Going forward we will endeavour to release 2 nuget packages \:

- **xlw**  -  For building Native (C/C++) xlls.
- **xlwDotNet** -  For building .NET (C#) xlls.

#### xlw
Right now we have released a dev (alpha) package on [xlw@nuget.org](https://www.nuget.org/packages/xlw). 
You'll just need to create a C++ DLL project and add the nuget package.

#### xlwDotNet
We have not yet released a xlwDotNet package, however you can find a first candidate at [xlwDotNet@sourceforge](https://sourceforge.net/projects/xlw/files/xlw/xlwDotNet.0.0.0-DEV08022113.nupkg/download).
To try out \:
1. Create a .NET Core Library project
2. Modify it to build for platforms x86 and\or x64. **Delete** the AnyCPU configuration
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>
</Project>
```
3. Add the xlwDotNet nuget package (it's not yet available on nuget.org)
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xlwDotNet" Version="0.0.0-DEV08022113" />
  </ItemGroup>
</Project>
```
4. Try adding the following code 
```csharp 
using System;
using xlwDotNet;
using xlwDotNet.xlwTypes;
namespace Example
{
    public class Class1
    {
        [ExcelExport("Hello World")]
        public static String HelloWorld()
        {
            return "Hello World!";
        }

        [ExcelExport("Get's .NET Version")]
        public static String dotnetversion()
        {
            return System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription;
        }

        [ExcelExport("Negate an cellmatrix")]
        public static CellMatrix Negate(
            [Parameter("My cell range")]  CellMatrix cellMatrix
            )
        {
            for(int i = 0; i < cellMatrix.RowsInStructure; ++i)
            {
                for (int j = 0; j < cellMatrix.ColumnsInStructure; ++j)
                {
                    if(cellMatrix[i,j].IsANumber)
                    {
                        cellMatrix[i, j] = new CellValue(-cellMatrix[i, j].NumericValue());
                    }
                }
            }
            return cellMatrix;
        }
        [ExcelExport("Negate an array")]
        public static MyArray NegateArray(
           [Parameter("My array")] MyArray myArray
           )
        {
            for (int i = 0; i < myArray.size; ++i)
            {
                myArray[i] = -myArray[i];
            }
            return myArray;
        }
    }
}
```
In your C# project file you set the ```TargetFramework``` to your choice of .NET version, for example
```xml
<PropertyGroup>
   <TargetFramework>net5.0</TargetFramework>
   <Platforms>x64</Platforms>
</PropertyGroup>
```
or 
```xml
<PropertyGroup>
   <TargetFramework>net472;netcoreapp3.1;net5.0</TargetFramework>
   <Platforms>x64;x86</Platforms>
</PropertyGroup>
```

## Remark
Please note that only the  MSVC Toolset **v142** is supported right now. Essentially you'll need Visual Studio 2019.

**Comment by Ninds** [comment]
First dev (alpha) package of xlwDotNet  has been uploaded to nuget.org
