### ISSUE TITLE
MyMatrix is not working well

### ISSUE THREAD

**Issue by lqexceldev** [xlw/xlw#4]
The Pre Release xlwDotNet is working fine using Framework 5.0, but when we use  MyMatrix, to do some operations, the function not return all values

**Comment by Ninds** [comment]
What is the precise problem that you observe?

I try with the following code :
```csharp
ExcelExport("My matrix function")]

        public static MyMatrix MyMatrixFunc(

           [Parameter("someMatrix")] MyMatrix m)

        {

            MyMatrix result = new MyMatrix(m.columns, m.rows);

            for (int i = 0; i < m.rows; i++)

            {

                for (int j = 0; j < m.columns; j++)

                {

                    result[j, i] = m[i, j];

                }

            }

            return result;
```
..with the project file 
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <TargetFramework>net5.0</TargetFramework>

    <Platforms>x86</Platforms>

  </PropertyGroup>

 

  <ItemGroup>

    <PackageReference Include="xlwDotNet" Version="20.8.5-DEV01f4" />

  </ItemGroup>

</Project>
```
It works fine 
![image001.png](https://user-images.githubusercontent.com/5892035/89500275-5f89a800-d7b9-11ea-86b5-c1e2c5930233.png)

**Comment by lqexceldev** [comment]
Hi Narinder,

 

I am using a similar code, but the result matrix, return only one value, not a complete matrix.

The final user don’t need to do special procedures, except insert the function.

 

 

Thanks,

Luis Quintana

**Comment by Ninds** [comment]
When an excel function returns an array, you must select a range of cells into which the result will be placed. 
If you only select one cell, you will only see one returned value.
If you look at my example, I select the range I5:K7 for the result.
Then you must also press **CTRL SHIFT RETURN** not just **RETURN**.

[Create an array formula](https://support.microsoft.com/en-us/office/create-an-array-formula-e43e12e0-afc6-4a12-bc7f-48361075954d)

**Comment by lqexceldev** [comment]
May be the Ctrl key has a bad configuration, let me check.

**Comment by lqexceldev** [comment]
Hi Narinder,

 

Was a problem in my keyboard like I suppose and said you in previous mail.

All is working very well.

 

Thanks very much.

**Comment by Ninds** [comment]
Welcome
