### ISSUE TITLE
Good stuff!

### ISSUE THREAD

**Issue by keithalewis** [xlw/xlw#5]
This should probably go in your wiki but I wasn't able to post there.
I have created a web version of [Macrofun.hlp](https://github.com/xlladdins/xll/blob/master/docs/Excel4Macros/README.md).
Hope you find that useful.

**Comment by keithalewis** [comment]
I cleaned this up a bit and made it available from [GitHub Pages](https://xlladdins.github.io/Excel4Macros/).

**Comment by Ninds** [comment]
Thanks

**Comment by keithalewis** [comment]
My pleasure. Glad to see you tending to xlw now. Keep up the good work.
