### ISSUE TITLE
URL in `xlw/XlfServices.h` comment is out of date

### ISSUE THREAD

**Issue by romanwerpachowski** [xlw/xlw#6]
The URL http://support.microsoft.com/kb/128185 provided in the comment for `XlfOper ShowDialogBox(const XlfOper& dialogData);` is out of date.

**Comment by keithalewis** [comment]
Here is a link for [DIALOG.BOX](https://xlladdins.github.io/Excel4Macros/dialog.box.html).
Note that DIALOG.BOX is not supported in 64-bit Excel.

**Comment by romanwerpachowski** [comment]
Thanks. Submitted a fix #9.
